@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
# @path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

### Route GET /person

GET {{baseUrl}}/profil/2


### Route POST /profil

POST {{baseUrl}}/profil
Content-Type: application/json

{
    "nickname": "jean louis",
    "email": "jl@yahoo.fr",
    "password": "js4life"
}

### Route POST /singup
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "nickname": "Chuck Norris",
    "email": "ChuckNorris@hotmail.fr",
    "password": "js4life"
}

### Route POST /login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "nickname": "Chuck Norris",
    "email": "ChuckNorris@hotmail.fr",
    "password": "js4life"
}

### Route DELETE /profil
DELETE {{baseUrl}}/profil/2
Content-Type: application/json

### Route GET /categories
GET {{baseUrl}}/category

### Route GET /category
GET {{baseUrl}}/category/1