@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
# @path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

#####################################  PROFIL  ######################################################

### Route GET /profils
GET {{baseUrl}}/profils

### Route GET /profil/:id
GET {{baseUrl}}/profil/24


### Route POST /profil
POST {{baseUrl}}/profil
Content-Type: application/json

{
    "nickname": "test modify",
    "email": "modify@email.fr",
    "password": "js4life"
}

### Route PUT /profil/:id

PUT {{baseUrl}}/profil/24
Content-Type: application/json

{
    "nickname": "test",
    "email":"tototest@email.fr"
}

### Route DELETE /profil
DELETE {{baseUrl}}/profil/58
Content-Type: application/json


##################################################  SIGNUP  ADMIN  LOGIN  ####################################################

### Route POST /signup
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "nickname": "louis",
    "email": "louis@louis.com",
    "password": "js4life"
}


### Route POST /login
POST {{baseUrl}}/login
Content-Type: application/json

{    "email": "mkjssd@lkjhzdc.com",
    "password": "js4life"
}

### Route GET /admin
GET  {{baseUrl}}/admin

### Route PUT /admin/profil/:id
PUT  {{baseUrl}}/admin/profil/19
Content-Type: application/json

{
    "role_id": 1
}

####################################### CATEGORY  #################################################################

### Route GET /categories
GET {{baseUrl}}/categories

### Route GET /category
GET {{baseUrl}}/category/1

######################################  ARTICLE  ###########################################################

### Route GET /article
GET {{baseUrl}}/articles

### Route GET /article
GET {{baseUrl}}/article/2


### Route POST /article
POST {{baseUrl}}/article
Content-Type: application/json

{
    "name": "Kinders test 2",
    "description": "Ceci est un article sur les Kinders",
    "content": "Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le ..."
}


### Route DELETE /article
DELETE {{baseUrl}}/article/4
Content-Type: application/json

### Route PUT /article/:id
PUT {{baseUrl}}/article/2
Content-Type: application/json

{
    "name": "Ferrero test modifier"
}

########################################  COMMENT  #######################################################

### Route GET /comments
GET {{baseUrl}}/comments

### Route GET /comment/id
GET {{baseUrl}}/comment/2

### Route POST /comment
POST {{baseUrl}}/comment
Content-Type: application/json

{
    "content": "Trop cool l'ajout de com !",
    "person_id": 6,
    "article_id": 2
}

### Route PUT /comment/:id
PUT {{baseUrl}}/comment/2
Content-Type: application/json

{
    "content": "Je modifie encore le commentaire"
}

### Route DELETE /comment
DELETE {{baseUrl}}/comment/3
Content-Type: application/json

##################################  MEDIA  ########################################################################

### Route GET /medias
GET {{baseUrl}}/medias

### Route GET /media/:id
GET {{baseUrl}}/media/5

### Route POST /media
POST {{baseUrl}}/media
Content-Type: application/json

{
    "link": "mljsqdmjnmsqdjdn"
}


### Route DELETE /media
DELETE {{baseUrl}}/media/6
Content-Type: application/json

### Route PUT /media/:id
PUT {{baseUrl}}/media/8
Content-Type: application/json

{
    "link": "j'ai encore modifié ton url"
}