@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
# @path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}


### Route GET /profils
GET {{baseUrl}}/profils

### Route GET /person
GET {{baseUrl}}/profil/10

### Route GET /profil/id
GET {{baseUrl}}/profil/2



### Route POST /profil
POST {{baseUrl}}/profil
Content-Type: application/json

{
    "nickname": "jean louis",
    "email": "jl@yahoo.fr",
    "password": "js4life"
}

### Route POST /signup
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "nickname": "nomad",
    "email": "nomad@nomad.com",
    "password": "Audy0714",
    "role_id": 2
}

### Route POST /login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "id": 54,
    "nickname": "nomad",
    "email": "nomad@nomad.com",
    "password": "Audy0714"
}

### Route PUT /profil/:id
PUT {{baseUrl}}/profil/54
Content-Type: application/json

{
    "email": "nomad@nomad.com"
}

### Route DELETE /profil
DELETE {{baseUrl}}/profil/2
Content-Type: application/json


### Route GET /admin
GET  {{baseUrl}}/admin

### Route GET /categories
GET {{baseUrl}}/categories

### Route GET /category
GET {{baseUrl}}/category/1

### Route GET /article
GET {{baseUrl}}/articles

### Route GET /article
GET {{baseUrl}}/article/2


### Route POST /article
POST {{baseUrl}}/article
Content-Type: application/json

{
    "name": "Kinders",
    "description": "Ceci est un article sur les Kinders",
    "content": "Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le ..."
}


### Route DELETE /article
DELETE {{baseUrl}}/article/6
Content-Type: application/json

### Route PUT /article/:id
PUT {{baseUrl}}/article/2
Content-Type: application/json

{
    "name": "Ferrero"
}

### Route GET /comments
GET {{baseUrl}}/comments

### Route GET /comment/id
GET {{baseUrl}}/comment/6

### Route POST /comment
POST {{baseUrl}}/comment
Content-Type: application/json

{
    "content": "Trop cool l'ajout de com !",
    "person_id": 6,
    "article_id": 2
}

### Route DELETE /comment
DELETE {{baseUrl}}/comment/7
Content-Type: application/json

### Route PUT /profil/:id
PUT {{baseUrl}}/comment/9
Content-Type: application/json

{
    "content": "Je modifie le commentaire",
    "person_id": 6,
    "article_id": 2
}