@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
# @path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

### Route GET /person

GET {{baseUrl}}/profil/2


### Route POST /profil

POST {{baseUrl}}/person
Content-Type: application/json

{
    "nickname": "Maher",
    "email": "m82.ayari@yahoo.fr",
    "password": "js4life"
}
